### ISSUE TITLE
Scrollbar on sidebar when minimized

### ISSUE THREAD

**Issue by cizbaker** [creativetimofficial/ct-now-ui-dashboard-pro#1]
When the sidebar on the left is minimised you can see a scrollbar however when it is extended again it disappears.

**Comment by cristijora** [comment]
While developing the Vue version of this dashboard, I also encountered this issue. This probably happens on Windows only. 
`now-ui-dashboard.js` line 32
`isWindows = navigator.platform.indexOf('Win') > -1 ? true : false;`
This doesn't work since navigator returns `Win32`

Potential solution:
`isWindows = navigator.platform.indexOf('Win32') > -1 ? true : false;`

Or to cover more such occurences:
`isWindows = navigator.platform.startsWith('Win');`
but this won't work on Internet Explorer because `startsWith` is not supported on IE.
You can add a polyfill for `startsWith`
```js
if (!window.String.prototype.startsWith) {
    String.prototype.startsWith = function(search, pos) {
      return this.substr(!pos || pos < 0 ? 0 : +pos, search.length) === search;
    };
 }
```
