### ISSUE TITLE
Selectpicker live search not working with now ui dashboard pro

### ISSUE THREAD

**Issue by fatheaddrummer** [creativetimofficial/ct-now-ui-dashboard-pro#14]
Hi there,

Thanks for the great Theme!!
Unfortunately the `data-live-search="true"` option of selectpicker is not working with now ui dashboard pro, altough it's working perfectly when I work without the theme....
It shows up, but the search is not working....could you please give it a check?

Thanks a lot!
Cheers, Christian

**Comment by dragosct** [comment]
Hi, @fatheaddrummer! Thank you for using our product. Please, can you tell me if the live search it's working for you without the theme on the BS4, I asking you this because this is the problem the library it's not updated for BS4 so that's the reason for the problem with live-search and other options for this library? Regards, Dragos

**Comment by fatheaddrummer** [comment]
Hi there and thanks for the reply! As far as I know it has been updated to BS4 a few weeks ago - I followed this case because I am often using the selectpicker plugin...
However, yes it works perfectly without the UI Theme on BS4!
Regards, Christian

**Comment by dragosct** [comment]
Hi, @fatheaddrummer! Perfect, please try to put the latest version of the plugin in assets/js/plugins/bootstrap-selectpicker.js and then try to see if the attribute data-search-live it's working. If this not works we will see then how to fix it. Regards, Dragos
