### ISSUE TITLE
Datatable.net row issues

### ISSUE THREAD

**Issue by pmm1899** [creativetimofficial/ct-now-ui-dashboard-pro#15]
Hi team,

I'd like to:
1) Set a hover style over Datatable's rows
2) Set a bg color on selected row

The file "now-ui-dashboard.css" says :
* Included libraries:
 *   DataTables 1.10.16, ColReorder 1.4.1, FixedColumns 3.2.3, FixedHeader 3.1.3, Responsive 2.2.0, RowGroup 1.0.2, RowReorder 1.2.3, Scroller 1.4.3, Select 1.2.3

However i can't see any css for Select library.

I followed this example:
https://datatables.net/examples/api/select_single_row.html

and I included file:
https://cdn.datatables.net/select/1.2.5/css/select.bootstrap4.min.css

but nothing happens.

ps : Sorry, for my bad english

**Comment by dragosct** [comment]
Hi, @pmm1899! Thank you for using our product. The Datatable's library it's not built by us so the js and the css are just generated by the datatables and we just import in our product. From what I noticed you don't have to introduce the select css because it's not required in the https://datatables.net/examples/api/select_single_row.html link, here you just have to introduce the javascript initalisation and that's it. Please try to use these files. 

[datatables.zip](https://github.com/creativetimofficial/now-ui-dashboard-pro/files/1859058/datatables.zip)

Regards,
Dragos

**Comment by pmm1899** [comment]
Hi Dragos, thanks for your reply.

If you take a look at the example on CSS tab, they use: 
https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css 

and in your project, you don't include it but you add some style for datatables.net on now-ui-dashboard.css.  I did not see any select style, so I tested both:

* Add jquery.dataTables.min.css  or
* Add custom style for datagrid row selection

It's working now. Thanks!!
Regards
Pmm
