### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ebisbe** [creativetimofficial/ct-now-ui-dashboard-pro#16]
Hello,

When building the now-ui-kit.scss I'm missing two files: 

```
 ERROR  Failed to compile with 2 errors      
These relative modules were not found:

* ../fonts/nucleo-outline.svg in ./node_modules/css-loader??ref--5-1!./node_modules/
postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./
assets/css/now-ui-kit.scss
* ../img/ink.png in ./node_modules/css-loader??ref--5-1!./node_modules/
postcss-loader/lib??ref--5-2!./node_modules/sass-loader/lib/loader.js??ref--5-3!./
assets/css/now-ui-kit.scss
```

**Comment by dragosct** [comment]
Hi, @ebisbe! Thank you for using our product. This line from the _nucleo-outline.scss partial `src: url('../fonts/nucleo-outline.svg');` must be deleted because we don't use SVG in the project and it will be deleted in the next update. Regard to the second error we don't use this image so maybe you call the image but it missing from your img files. 

Regards,
Dragos

**Comment by ebisbe** [comment]
@dragosct10 both lines are taken straight from your .zip file. If they are not needed I will delete them but wanted to let you now for future updates.

**Comment by dragosct** [comment]
Hi, @ebisbe! Thank you very much for your observation. Yes, we will clean the archive in the next update. Regards, Dragos
