### ISSUE TITLE
Radio input with several lines

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#21]
Hi, I would like to put several lines to my input radio, but it does not work, the point is not displayed anymore ...

Example: http://klam.shost.ca/test/

Regards

**Comment by dragosct** [comment]
Hi, @KonScyence! Thank you for using our product. You must put the forms like on our [page](https://demos.creative-tim.com/now-ui-dashboard-pro/examples/forms/regular.html) at inline checkboxes section. Regards, Dragos

**Comment by KonScyence** [comment]
Hi @dragosct10, What I mean is that I want several input radio, one below the other. However, I want them with images and text ...

Example: http://klam.shost.ca/test/

The problem is that in this case, the radio button is no longer clickable.

Regards

**Comment by dragosct** [comment]
Hi! It's working but you have to put the code like below image, because the input tag must be followed below by the span tag with class .form-check-sign. 

<img width="437" alt="screen shot 2018-06-05 at 09 47 57" src="https://user-images.githubusercontent.com/17456857/40959535-9ddee8f2-68a5-11e8-9716-39e52e8ad6f0.png">

Regards, 
Dragos
