### ISSUE TITLE
Select-picker v1.13.1 released and not fully compatible with Now UI Dashboard

### ISSUE THREAD

**Issue by deksden** [creativetimofficial/ct-now-ui-dashboard-pro#23]
Hi! New version of plugin with important updates and DB4 support released, but currently not fully compatible with your product! Please, schedule update for this plugin. 

Here is updated versions: 
https://github.com/snapappointments/bootstrap-select/releases

P.s.: why name it bootstrap-selectpicker while "official" name is just bootstrap-select?

**Comment by dragosct** [comment]
Hi, @deksden! Thank you for using our product. Yes, you are right but this is a little annoying because we waited on this [repo](https://github.com/silviomoreto/bootstrap-select/releases) to see if a new version has arrived because the library is made by Silvio Moreto and if you will see on this repo the latest version is 1.13.0 alpha and I don't know why he doesn't update his repo. Anyway, we will introduce the library in the next update because we must to test it and to make the style for it. Thank you again! 

Regards, 
Dragos

**Comment by deksden** [comment]
I m also was confused by changing repo "owner", but same person contribute to both repositories, so, not sure what happened)))

P.S. Stats confirm this: https://github.com/silviomoreto/bootstrap-select/graphs/contributors
