### ISSUE TITLE
Datatable minor bug with select field of length menu

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#35]
Hi, if you click on the text of the length menu, the focus of the select field is activated:
![length menu](https://user-images.githubusercontent.com/27307704/42735344-262c6178-8820-11e8-87ef-afd76065761d.gif)

Also, the arrow of the select field doesn't turn:
![arrowturn](https://user-images.githubusercontent.com/27307704/42735368-71653eda-8820-11e8-8660-36c1d6e568bd.gif)

Regards!

**Comment by dragosct** [comment]
Hi! Thank you for this issue. Yes, you are right about the first issue the focus is activated but there is something a little bit complicated from what I saw because all the code from the toolbar are coming from the datatables.net library and is not so manageable but we will try to see what can be done there. Regard on the arrow that doesn't turn when is pressed the input I'm not sure what version did you use because on our side the input it looks like this: 
<img width="195" alt="screen shot 2018-07-16 at 11 28 07" src="https://user-images.githubusercontent.com/17456857/42749504-8fc215d4-88ec-11e8-8657-cc5bbe984829.png">

Regards, 
Dragos

**Comment by KonScyence** [comment]
Hi! I use the latest one, at https://demos.creative-tim.com/now-ui-dashboard-pro/examples/tables/datatables.net.html

![creativedata](https://user-images.githubusercontent.com/27307704/42762789-35200bfc-88df-11e8-83ac-1cdc8b19cfe5.PNG)


Also, it seems different with every browser:
Chrome:
![capturechrome](https://user-images.githubusercontent.com/27307704/42762977-c3645486-88df-11e8-987e-4dda26b0bfcd.PNG)

Internet explorer:
![captureexplorer](https://user-images.githubusercontent.com/27307704/42762978-c375624e-88df-11e8-9073-f643a03c3d98.PNG)

Firefox:
![capturefirefox](https://user-images.githubusercontent.com/27307704/42762979-c387c5a6-88df-11e8-880e-def4816bc880.PNG)

Opera:
![captureopera](https://user-images.githubusercontent.com/27307704/42762980-c39c2d2a-88df-11e8-8da6-7dd4605ba6b7.PNG)

Everything tried on windows.

Regards

**Comment by dragosct** [comment]
Hi! It's very weird because on my MacBook it looks like below image and I think it's depend on the Os but anyway this select is coming from the library: 

<img width="1440" alt="screen shot 2018-07-17 at 12 55 40" src="https://user-images.githubusercontent.com/17456857/42810538-d88b6c00-89c0-11e8-9c41-09470825c406.png">

Regards,
Dragos
