### ISSUE TITLE
Bootstrap tags input not updated

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#37]
Hi, you will tell me that you have the latest version for the plugin (0.8.0) and well you are right theoretically! However, if you go see on the [github of the project](https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/blob/master/dist/bootstrap-tagsinput.js#L43), it's not the same file (Example: line 43 has been added).

So I advise to put the REAL latest version!

Regards!

**Comment by dragosct** [comment]
Hi, @KonScyence! This is quite interesting because I see that the plugin it's a little changed but I can't understand why because we just changed the  `return 'label label-info';` to `return 'badge';` for the function that  I build for colors of the tags, but anyway very good observation thank you, I will change in the next update which I think will be next week. 

Regards, 
Dragos
