### ISSUE TITLE
Not able to catch the dropdown value

### ISSUE THREAD

**Issue by KonScyence** [creativetimofficial/ct-now-ui-dashboard-pro#38]
Hi, I don't know what I'm doing wrong with this plugin, but I try to select the value selected in the drop-down menu, however, it always gives me the same thing, the first option.

Example: https://codepen.io/KonScyence/pen/OwWwML

N.B I sent a message on the author's github too, but  nobody seems to answer the issues...

Regards

**Comment by dragosct** [comment]
Hi, @KonScyence! What is happening now it's normal because like you see in the image below all of your options are set with an attribute of value `0`.

<img width="422" alt="screen shot 2018-07-23 at 11 53 18" src="https://user-images.githubusercontent.com/17456857/43067317-b882da20-8e6f-11e8-82a5-e5598ca9d191.png">

Regards,
Dragos

**Comment by KonScyence** [comment]
Ahhhh ... Sorry, I was probably tired that day ^^
