### ISSUE TITLE
Bootstrap Tooltips

### ISSUE THREAD

**Issue by justinledelson** [creativetimofficial/ct-now-ui-dashboard-pro#40]
My Tooltips all appear off-center.

![image](https://user-images.githubusercontent.com/2658766/43873662-3f0c8ea0-9b3c-11e8-9055-7dcceb2e3514.png)

**Comment by dragosct** [comment]
Hi, @justinledelson! Thank you for using our product. Please give us your link to the project to see exactly what is happening there. Regards, Dragos

**Comment by justinledelson** [comment]
Found this to be an issue with perfectScrollbar. Once I disabled the plugin the "tooltip off-center" bug disappeared as well as a few other weird issues. I recommend we get rid of this plugin.

**Comment by dragosct** [comment]
Hi, @justinledelson! Thank you for this answer. We must see how we can fix this conflict between these tooltips and perfectScrollbar because if we remove this plugin the scrollbar from windows will look very weird or maybe we will find another plugin like this to replace pefectScrollbar. Regards, Dragos

**Comment by justinledelson** [comment]
@dragosct10 I recommend you just style the scrollbar using CSS. Just my thought though.
