### ISSUE TITLE
Few issues with now-ui-dashboard-pro

### ISSUE THREAD

**Issue by AJ-Skywalker** [creativetimofficial/ct-now-ui-dashboard-pro#53]
Hi!

Happy New Year!

I purchased the now ui dashboard, and ran into few issues when implemented:

1. In a responsive mode when I decrease the window width, at some point of time the header area (where navbar is) turns white. This also happens when I open the page in mobile view. On mobile view, initially it shows the dark blue gradient background, but I scroll down and then go up, it shows the navbar area in white.

2. I did not see a page design without left menu. I have couple of pages where I want to continue using color theme but does not need any menu items.

3. The icons in the left menu and icon + text the expanded menu are too light. Any way to enhance that?

4. I want to exclude few tags from the now ui to have the content as I want it. Though I am not sure how can I do that without modifying the now ui css. I'm keeping it as is to accommodate the future updates from your side, and that I do not have to remember what changes I did.

5. I need a page where I have content window split into 30:70 view where left will have filters and the right pane will have results list. I did not see this kind of page either, please share with me at the earliest.

6. I want a custom color used for the left menu, and for the buttons, links, divs etc. Please guide me how I can incorporate that without disturbing the now ui css and the way to use it in the pages. I know how to define colors and create css, just not sure what would be the best and safe way to  override the standard colors provided.

7. The outline buttons are not working. I tried implementing with the included bootstrap css but it is getting overridden somewhere. 

8. I want a logo where the page title is, and want to push the page title down. Please help with this as I do not have a logo that I can fit on the left menu. One of the problem is that the template takes text as logo image part and logo text part, but its not possible with the logo I have and I need to put the full logo into that area. This is where I thought I can have logo image where page title is and push the page title down.

9. The area where text logo is displayed in template gets round effect. Any way I can have that in the square shape?

Thanks!
Aniket.

**Comment by AJ-Skywalker** [comment]
I also wanted to ask how to post this to the Zendesk support as indicated on the support page.

**Comment by dragosct** [comment]
Hi, @AJ-Skywalker! Thank you for using our products and sorry for the late response. You can access our contact us form on this [page](https://www.creative-tim.com/contact-us). Now from what I noticed many of your requests are not just issues, are just things that you want to change or add in your project. 

1. For the first point please can you show us some screenshots because it's hard to figure out just from the your explanation. 

2. You have the static pages without the left menu. You can find them in `examples/pages/`.
3. Here can you please be more explicit about it? 
4. What tags do you want to exclude, please be more explicit? 
5. We can't help you with this because the product contains exactly the pages that you saw on our sire and now it depends on you how to change the layout of the pages, you can make any changes that you want. 
6. The custom color for the sidebar can be changed from `assets/scss/now-ui-dashboard/_sidebar-and-main-panel.scss ` and the buttons colors from the `assets/scss/now-ui-dashboard/_buttons.scss ` and to do that you have to create new variables with colors and put them in the specified locations. 
7. The outline buttons are not implemented in our product, in the product are visible only the visible components, maybe in the next updates we will implement them. 
8. You can put an image there where the logo text it's present with the `img` tag and with small css styling it will fit fine there. 
9. I can't figured out about what round effect do you refer, please be more specific.

Regards, 
Dragos
